services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  ms-housekeeping:
    build: ./ms-housekeeping
    container_name: ms-housekeeping
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-reportes:
    build: ./ms-reportes
    container_name: ms-reportes
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  ms-notificaciones:
    build: ./ms-notificaciones
    container_name: ms-notificaciones
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server