spring.application.name=api-gateway
server.port=8090

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=ms-auth
spring.cloud.gateway.routes[0].uri=lb://ms-auth
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=ms-clientes
spring.cloud.gateway.routes[1].uri=lb://ms-clientes
spring.cloud.gateway.routes[1].predicates[0]=Path=/clientes/**

spring.cloud.gateway.routes[2].id=ms-reservas
spring.cloud.gateway.routes[2].uri=lb://ms-reservas
spring.cloud.gateway.routes[2].predicates[0]=Path=/reservas/**

spring.cloud.gateway.routes[3].id=ms-pagos
spring.cloud.gateway.routes[3].uri=lb://ms-pagos
spring.cloud.gateway.routes[3].predicates[0]=Path=/pagos/**

spring.cloud.gateway.routes[4].id=ms-hoteles
spring.cloud.gateway.routes[4].uri=lb://ms-hoteles
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/hoteles/**

spring.cloud.gateway.routes[5].id=ms-habitaciones
spring.cloud.gateway.routes[5].uri=lb://ms-habitaciones
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/habitaciones/**

spring.cloud.gateway.routes[6].id=ms-servicios
spring.cloud.gateway.routes[6].uri=lb://ms-servicios
spring.cloud.gateway.routes[6].predicates[0]=Path=/api/servicios/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG