server.port=8083
spring.application.name=ms-pagos

# ============================================
# OPCIÓN 1: MySQL corriendo en DOCKER (puerto 3312 mapeado al host)
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/db_pagos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ============================================
# OPCIÓN 2: MySQL corriendo en XAMPP (puerto 3306, sin password)
# Para usar esta opción: comenta las 3 líneas de arriba (OPCIÓN 1)
# y descomenta las 3 líneas de abajo.
# ============================================
#spring.datasource.url=jdbc:mysql://localhost:3306/db_pagos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# --- AGREGA ESTA LÍNEA ---
spring.flyway.baseline-on-migrate=true

# LOCAL: Eureka corriendo en Docker con puerto expuesto
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.htmldoc.swagger-ui.path=/doc/swagger-ui.html