spring.application.name=ms-habitaciones
server.port=8086

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:mysql://mysql-habitaciones:3306/db_habitaciones?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true