spring.application.name=ms-hoteles
server.port=8085

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:mysql://mysql-hoteles:3306/db_hoteles?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true