CREATE TABLE IF NOT EXISTS usuario (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   nombre VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    rol VARCHAR(50)
    );